### ISSUE TITLE
The "Mute" button flies up when adding a stream

### ISSUE THREAD

**Issue by Nureckiy** [aullman/opentok-layout-js#100]
![mute-bug](https://user-images.githubusercontent.com/17616120/135595617-d59b438c-f7ec-42b3-b2d2-53c936a501a5.gif)
When a new stream is added, the mute control is placed at the bottom of the stream element and begins to move upward with a transition.
Can't reproduce the issue without using a layout library.

Are there any ways to avoid this? Thanks in advance!

opentok-layout-js v4.2.0
Browser: Google chrome for windows, v94.0.4606.61

**Comment by aullman** [comment]
Oh wow, it does too, that's new. I didn't notice because I'm not using that default UI. OpenTok have changed the CSS which is making it happen. This is the CSS that's causing it to happen.

```css
.OT_publisher .OT_edge-bar-item, .OT_subscriber .OT_edge-bar-item {
    transition-property: none !important;
    transition-duration: 0.5s;
    transition-timing-function: ease-in;
}
```

You can probably override it with something like:


```css
.OT_publisher .OT_edge-bar-item, .OT_subscriber .OT_edge-bar-item {
  transition: none !important;
}
```
